// Emoji Decoder puzzle bank — seeded into SQLite on startup.

module.exports = [
  { emojis: "🦁👑", answer: "The Lion King", category: "Movie", hint: "Disney classic" },
  { emojis: "⭐️⚔️", answer: "Star Wars", category: "Movie", hint: "A galaxy far far away" },
  { emojis: "🕷️🧑", answer: "Spider-Man", category: "Movie", hint: "Friendly neighborhood hero" },
  { emojis: "🧊❄️👸", answer: "Frozen", category: "Movie", hint: "Let it go" },
  { emojis: "🏠⬆️🎈", answer: "Up", category: "Movie", hint: "Pixar tearjerker" },
  { emojis: "🦈🌊", answer: "Jaws", category: "Movie", hint: "You're gonna need a bigger boat" },
  { emojis: "👻👻🔫", answer: "Ghostbusters", category: "Movie", hint: "Who you gonna call?" },
  { emojis: "🧙‍♂️💍", answer: "Lord of the Rings", category: "Movie", hint: "One ring to rule them all" },
  { emojis: "🦇🧑‍🦲", answer: "Batman", category: "Movie", hint: "Dark Knight" },
  { emojis: "🚢❄️💑", answer: "Titanic", category: "Movie", hint: "I'm the king of the world" },
  { emojis: "🎃🔪", answer: "Halloween", category: "Movie", hint: "Spooky slasher" },
  { emojis: "🐀👨‍🍳", answer: "Ratatouille", category: "Movie", hint: "Anyone can cook" },
  { emojis: "🏝️🦕", answer: "Jurassic Park", category: "Movie", hint: "Life finds a way" },
  { emojis: "🤖❤️🌱", answer: "Wall-E", category: "Movie", hint: "Lonely robot" },
  { emojis: "🎵🎤👩‍🎤⭐", answer: "A Star Is Born", category: "Movie", hint: "Musical drama" },
  { emojis: "🍕🐢🥷", answer: "Teenage Mutant Ninja Turtles", category: "Show", hint: "Cowabunga!" },
  { emojis: "🔴💊🔵💊", answer: "The Matrix", category: "Movie", hint: "Red pill or blue pill" },
  { emojis: "🧹⚡🏰", answer: "Harry Potter", category: "Movie", hint: "You're a wizard" },
  { emojis: "🐠🔍", answer: "Finding Nemo", category: "Movie", hint: "Just keep swimming" },
  { emojis: "👨‍🚀🌙", answer: "Apollo 13", category: "Movie", hint: "Houston we have a problem" },
  { emojis: "🎪🐘", answer: "Dumbo", category: "Movie", hint: "Flying elephant" },
  { emojis: "🧟‍♂️🌍", answer: "World War Z", category: "Movie", hint: "Zombie apocalypse" },
  { emojis: "🏎️💨", answer: "Fast and Furious", category: "Movie", hint: "Family" },
  { emojis: "🐒👑🌴", answer: "Tarzan", category: "Movie", hint: "Raised by apes" },
  { emojis: "🎭😂😭", answer: "Inside Out", category: "Movie", hint: "Emotions as characters" },
  { emojis: "☕️👫👫👫", answer: "Friends", category: "Show", hint: "I'll be there for you" },
  { emojis: "🧪💎👨‍🔬", answer: "Breaking Bad", category: "Show", hint: "Say my name" },
  { emojis: "👑🐉🏰⚔️", answer: "Game of Thrones", category: "Show", hint: "Winter is coming" },
  { emojis: "🍌💰🏗️", answer: "Arrested Development", category: "Show", hint: "There's always money in the..." },
  { emojis: "🧟‍♂️🚶‍♂️", answer: "The Walking Dead", category: "Show", hint: "Zombie survival" },
  { emojis: "🦖🚗⚡", answer: "Back to the Future", category: "Movie", hint: "88 miles per hour" },
  { emojis: "🤠🚀👨‍🚀", answer: "Toy Story", category: "Movie", hint: "To infinity and beyond" },
  { emojis: "🟢👹🐴", answer: "Shrek", category: "Movie", hint: "Ogres have layers" },
  { emojis: "🦍🏢✈️", answer: "King Kong", category: "Movie", hint: "Eighth wonder of the world" },
  { emojis: "🐼🥋", answer: "Kung Fu Panda", category: "Movie", hint: "Skadoosh" },
  { emojis: "🧞‍♂️🪔🐒", answer: "Aladdin", category: "Movie", hint: "A whole new world" },
  { emojis: "🐉🏍️🔥", answer: "How to Train Your Dragon", category: "Movie", hint: "Toothless" },
  { emojis: "🏨💀👦", answer: "The Shining", category: "Movie", hint: "Here's Johnny!" },
  { emojis: "👽📞🚲", answer: "E.T.", category: "Movie", hint: "Phone home" },
  { emojis: "🃏🦇🌃", answer: "The Dark Knight", category: "Movie", hint: "Why so serious?" },
  { emojis: "💍🌋🧝", answer: "Return of the King", category: "Movie", hint: "Third in the trilogy" },
  { emojis: "🚪🦁🧙‍♀️❄️", answer: "Narnia", category: "Movie", hint: "Through the wardrobe" },
  { emojis: "🐝🎬", answer: "Bee Movie", category: "Movie", hint: "According to all known laws of aviation..." },
  { emojis: "🏃🍫🦐", answer: "Forrest Gump", category: "Movie", hint: "Life is like a box of chocolates" },
  { emojis: "😱🏠🚿🔪", answer: "Psycho", category: "Movie", hint: "Hitchcock classic" },
  { emojis: "🚂❄️🔍", answer: "Murder on the Orient Express", category: "Movie", hint: "Poirot mystery" },
  { emojis: "🤡🎈🚣", answer: "It", category: "Movie", hint: "You'll float too" },
  { emojis: "🦸‍♂️🦸‍♀️👨‍👩‍👧‍👦", answer: "The Incredibles", category: "Movie", hint: "Super family" },
  { emojis: "🌃💃🕺🎹", answer: "La La Land", category: "Movie", hint: "City of stars" },
  { emojis: "🐙🏴‍☠️⚓", answer: "Pirates of the Caribbean", category: "Movie", hint: "Captain Jack Sparrow" },
  { emojis: "🤖🕶️🔫", answer: "The Terminator", category: "Movie", hint: "I'll be back" },
  { emojis: "🪐👨‍🚀🌽", answer: "Interstellar", category: "Movie", hint: "Love transcends time" },
  { emojis: "🎩🍫🏭", answer: "Charlie and the Chocolate Factory", category: "Movie", hint: "Golden ticket" },
  { emojis: "👸🐸💋", answer: "The Princess and the Frog", category: "Movie", hint: "Kiss changes everything" },
  { emojis: "🔍🐟🌊💙", answer: "Finding Dory", category: "Movie", hint: "Forgetful fish" },
  { emojis: "🇫🇷👩‍🍳🐭", answer: "Ratatouille", category: "Movie", hint: "Paris kitchen" },
  { emojis: "📋💼😴", answer: "The Office", category: "Show", hint: "Dunder Mifflin" },
  { emojis: "🛳️⚓🏝️✈️", answer: "Lost", category: "Show", hint: "Mystery island" },
  { emojis: "👨‍👩‍👦👨‍👨‍👧🍷", answer: "Modern Family", category: "Show", hint: "Mockumentary sitcom" },
  { emojis: "🐉🎮👾", answer: "Stranger Things", category: "Show", hint: "The Upside Down" },
  { emojis: "🚀🧑‍🔬🍕", answer: "Rick and Morty", category: "Show", hint: "Wubba lubba dub dub" },
  { emojis: "👨‍⚕️🏥😷", answer: "House", category: "Show", hint: "It's never lupus" },
  { emojis: "🗡️⚔️🛡️🏰", answer: "The Witcher", category: "Show", hint: "Toss a coin" },
  { emojis: "💰🎭🔫🇪🇸", answer: "Money Heist", category: "Show", hint: "Bella ciao" },
  { emojis: "🦑🎮💵", answer: "Squid Game", category: "Show", hint: "Red light, green light" },
  { emojis: "👨‍🍳🔪🍔😡", answer: "The Bear", category: "Show", hint: "Yes, chef!" },
];
