// Hot Takes / Would You Rather prompt bank — seeded into SQLite on startup.

module.exports = [
  { question: "Would you rather...", optionA: "Be able to fly", optionB: "Be able to read minds" },
  { question: "Would you rather...", optionA: "Live without music", optionB: "Live without movies" },
  { question: "Would you rather...", optionA: "Always be 10 minutes late", optionB: "Always be 20 minutes early" },
  { question: "Would you rather...", optionA: "Have unlimited money", optionB: "Have unlimited time" },
  { question: "Would you rather...", optionA: "Live in the mountains", optionB: "Live by the beach" },
  { question: "Would you rather...", optionA: "Be famous", optionB: "Be the best friend of someone famous" },
  { question: "Would you rather...", optionA: "Travel to the past", optionB: "Travel to the future" },
  { question: "Would you rather...", optionA: "Only eat pizza forever", optionB: "Never eat pizza again" },
  { question: "Would you rather...", optionA: "Have super strength", optionB: "Have super speed" },
  { question: "Would you rather...", optionA: "Know every language", optionB: "Play every instrument" },
  { question: "Would you rather...", optionA: "Never use social media again", optionB: "Never watch a movie again" },
  { question: "Would you rather...", optionA: "Be the funniest person in the room", optionB: "Be the smartest person in the room" },
  { question: "Would you rather...", optionA: "Have a personal chef", optionB: "Have a personal trainer" },
  { question: "Would you rather...", optionA: "Always know the truth", optionB: "Always get away with lying" },
  { question: "Would you rather...", optionA: "Live in a tiny home", optionB: "Live in a mansion you must clean yourself" },
  { question: "Would you rather...", optionA: "Speak to animals", optionB: "Speak every human language" },
  { question: "Would you rather...", optionA: "Be invisible whenever you want", optionB: "Teleport anywhere instantly" },
  { question: "Would you rather...", optionA: "Never feel pain", optionB: "Never feel fear" },
  { question: "Would you rather...", optionA: "Win the lottery", optionB: "Live twice as long" },
  { question: "Would you rather...", optionA: "Have free flights forever", optionB: "Have free food forever" },
  { question: "Would you rather...", optionA: "Be a famous actor", optionB: "Be a famous musician" },
  { question: "Would you rather...", optionA: "Give up coffee forever", optionB: "Give up dessert forever" },
  { question: "Would you rather...", optionA: "Work your dream job for low pay", optionB: "Work a boring job for huge pay" },
  { question: "Would you rather...", optionA: "Re-live one perfect day forever", optionB: "Never repeat a single day"},
  { question: "Would you rather...", optionA: "Fight one horse-sized duck", optionB: "Fight 100 duck-sized horses" },
  { question: "Would you rather...", optionA: "Always sing instead of speak", optionB: "Always dance while walking" },
  { question: "Would you rather...", optionA: "Live without the internet", optionB: "Live without air conditioning and heating" },
  { question: "Would you rather...", optionA: "Be 10 years older", optionB: "Be 5 years younger" },
  { question: "Would you rather...", optionA: "Have a rewind button for life", optionB: "Have a pause button for life" },
  { question: "Would you rather...", optionA: "Be stranded on an island alone", optionB: "Be stranded with someone you dislike" },
  { question: "Would you rather...", optionA: "Lose your sense of taste", optionB: "Lose your sense of smell" },
  { question: "Would you rather...", optionA: "Read minds but can't turn it off", optionB: "See 10 minutes into the future once a day" },
  { question: "Would you rather...", optionA: "Live in space", optionB: "Live under the sea" },
  { question: "Would you rather...", optionA: "Have hands for feet", optionB: "Have feet for hands" },
  { question: "Would you rather...", optionA: "Never wait in line again", optionB: "Never hit traffic again" },
  { question: "Would you rather...", optionA: "Be a master of every sport", optionB: "Be a master of every board game" },
  { question: "Would you rather...", optionA: "Get one free wish now", optionB: "Get three wishes in 10 years" },
  { question: "Would you rather...", optionA: "Sleep 4 hours and feel rested", optionB: "Need 10 hours but dream anything you want" },
  { question: "Would you rather...", optionA: "Own a dragon", optionB: "Be a dragon" },
  { question: "Would you rather...", optionA: "Have unlimited battery on all devices", optionB: "Have unlimited free Wi-Fi anywhere" },

  { question: "Hot take:", optionA: "Pineapple belongs on pizza", optionB: "Pineapple does NOT belong on pizza" },
  { question: "Hot take:", optionA: "Cats are better than dogs", optionB: "Dogs are better than cats" },
  { question: "Hot take:", optionA: "Morning person", optionB: "Night owl" },
  { question: "Hot take:", optionA: "Books are better than movies", optionB: "Movies are better than books" },
  { question: "Hot take:", optionA: "Summer is the best season", optionB: "Winter is the best season" },
  { question: "Hot take:", optionA: "Cereal first, then milk", optionB: "Milk first, then cereal" },
  { question: "Hot take:", optionA: "The toilet paper goes over", optionB: "The toilet paper goes under" },
  { question: "Hot take:", optionA: "Texting is better than calling", optionB: "Calling is better than texting" },
  { question: "Hot take:", optionA: "A hotdog is a sandwich", optionB: "A hotdog is NOT a sandwich" },
  { question: "Hot take:", optionA: "Android is better", optionB: "iPhone is better" },
  { question: "Hot take:", optionA: "Working from home wins", optionB: "Working from the office wins" },
  { question: "Hot take:", optionA: "Sweet snacks beat salty", optionB: "Salty snacks beat sweet" },
  { question: "Hot take:", optionA: "Water is best ice cold", optionB: "Room temperature water is fine" },
  { question: "Hot take:", optionA: "Die Hard is a Christmas movie", optionB: "Die Hard is NOT a Christmas movie" },
  { question: "Hot take:", optionA: "Window seat", optionB: "Aisle seat" },
  { question: "Hot take:", optionA: "Showers in the morning", optionB: "Showers at night" },
  { question: "Hot take:", optionA: "Mint chocolate is delicious", optionB: "Mint chocolate tastes like toothpaste" },
  { question: "Hot take:", optionA: "Board games beat video games", optionB: "Video games beat board games" },
  { question: "Hot take:", optionA: "Breakfast food anytime", optionB: "Breakfast food only at breakfast" },
  { question: "Hot take:", optionA: "Socks with sandals can work", optionB: "Socks with sandals: never" },
];
