// Trivia question bank — seeded into SQLite on startup.
// options is an array of 4 strings; correctIndex points at the right one.

module.exports = [
  // Geography
  { question: "What is the capital of Australia?", options: ["Sydney", "Melbourne", "Canberra", "Brisbane"], correctIndex: 2, category: "Geography" },
  { question: "What is the largest ocean on Earth?", options: ["Atlantic Ocean", "Indian Ocean", "Arctic Ocean", "Pacific Ocean"], correctIndex: 3, category: "Geography" },
  { question: "What is the smallest country in the world?", options: ["Monaco", "Vatican City", "San Marino", "Liechtenstein"], correctIndex: 1, category: "Geography" },
  { question: "What is the longest river in the world?", options: ["Amazon", "Nile", "Yangtze", "Mississippi"], correctIndex: 1, category: "Geography" },
  { question: "What is the currency of Japan?", options: ["Yuan", "Won", "Yen", "Ringgit"], correctIndex: 2, category: "Geography" },
  { question: "Which continent is the Sahara Desert on?", options: ["Asia", "South America", "Africa", "Australia"], correctIndex: 2, category: "Geography" },
  { question: "Which country has the Great Barrier Reef?", options: ["Indonesia", "Philippines", "Australia", "Thailand"], correctIndex: 2, category: "Geography" },
  { question: "Which country has the most natural lakes?", options: ["Russia", "Canada", "USA", "Finland"], correctIndex: 1, category: "Geography" },
  { question: "What is the capital of Canada?", options: ["Toronto", "Vancouver", "Ottawa", "Montreal"], correctIndex: 2, category: "Geography" },
  { question: "Mount Everest sits on the border of Nepal and which country?", options: ["India", "China", "Bhutan", "Pakistan"], correctIndex: 1, category: "Geography" },
  { question: "Which is the only continent with land in all four hemispheres?", options: ["Asia", "Africa", "South America", "Europe"], correctIndex: 1, category: "Geography" },
  { question: "What is the capital of Brazil?", options: ["Rio de Janeiro", "São Paulo", "Brasília", "Salvador"], correctIndex: 2, category: "Geography" },
  { question: "Which US state is the largest by area?", options: ["Texas", "California", "Alaska", "Montana"], correctIndex: 2, category: "Geography" },
  { question: "The ancient city of Petra is located in which country?", options: ["Egypt", "Jordan", "Israel", "Syria"], correctIndex: 1, category: "Geography" },
  { question: "Which country is both in Europe and Asia?", options: ["Greece", "Turkey", "Poland", "Romania"], correctIndex: 1, category: "Geography" },
  { question: "What is the deepest point in the world's oceans?", options: ["Tonga Trench", "Java Trench", "Mariana Trench", "Puerto Rico Trench"], correctIndex: 2, category: "Geography" },
  { question: "Which African country has the largest population?", options: ["Egypt", "Ethiopia", "South Africa", "Nigeria"], correctIndex: 3, category: "Geography" },
  { question: "Venice is famous for what kind of streets?", options: ["Cobblestone", "Canals", "Tunnels", "Bridges only"], correctIndex: 1, category: "Geography" },
  { question: "Which country gifted the Statue of Liberty to the USA?", options: ["England", "Spain", "France", "Italy"], correctIndex: 2, category: "Geography" },
  { question: "What is the capital of New Zealand?", options: ["Auckland", "Wellington", "Christchurch", "Queenstown"], correctIndex: 1, category: "Geography" },

  // Science
  { question: "Which planet is known as the Red Planet?", options: ["Venus", "Mars", "Jupiter", "Saturn"], correctIndex: 1, category: "Science" },
  { question: "What element does 'O' represent on the periodic table?", options: ["Osmium", "Oxygen", "Gold", "Oganesson"], correctIndex: 1, category: "Science" },
  { question: "What is the hardest natural substance on Earth?", options: ["Gold", "Iron", "Diamond", "Platinum"], correctIndex: 2, category: "Science" },
  { question: "What is the chemical formula for water?", options: ["CO2", "H2O", "NaCl", "O2"], correctIndex: 1, category: "Science" },
  { question: "Which gas do plants absorb?", options: ["Oxygen", "Nitrogen", "Carbon Dioxide", "Hydrogen"], correctIndex: 2, category: "Science" },
  { question: "Who developed the theory of relativity?", options: ["Isaac Newton", "Niels Bohr", "Albert Einstein", "Stephen Hawking"], correctIndex: 2, category: "Science" },
  { question: "Which planet has the most moons?", options: ["Jupiter", "Saturn", "Uranus", "Neptune"], correctIndex: 1, category: "Science" },
  { question: "How many bones in the adult human body?", options: ["186", "206", "226", "246"], correctIndex: 1, category: "Science" },
  { question: "What does DNA stand for?", options: ["Deoxyribonucleic Acid", "Dinitrogen Acid", "Dynamic Nuclear Acid", "Dioxin Nucleic Acid"], correctIndex: 0, category: "Science" },
  { question: "What is the speed of light approximately?", options: ["300,000 km/s", "150,000 km/s", "500,000 km/s", "100,000 km/s"], correctIndex: 0, category: "Science" },
  { question: "What is the boiling point of water in Celsius?", options: ["90°C", "100°C", "110°C", "120°C"], correctIndex: 1, category: "Science" },
  { question: "What is the most abundant gas in Earth's atmosphere?", options: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Argon"], correctIndex: 2, category: "Science" },
  { question: "What part of the cell contains genetic material?", options: ["Mitochondria", "Nucleus", "Ribosome", "Cytoplasm"], correctIndex: 1, category: "Science" },
  { question: "What force keeps planets in orbit around the Sun?", options: ["Magnetism", "Friction", "Gravity", "Inertia"], correctIndex: 2, category: "Science" },
  { question: "What is the chemical symbol for gold?", options: ["Go", "Gd", "Au", "Ag"], correctIndex: 2, category: "Science" },
  { question: "How many chambers does the human heart have?", options: ["2", "3", "4", "5"], correctIndex: 2, category: "Science" },
  { question: "What type of animal is a Komodo dragon?", options: ["Snake", "Lizard", "Crocodile", "Salamander"], correctIndex: 1, category: "Science" },
  { question: "What vitamin does sunlight help the body produce?", options: ["Vitamin A", "Vitamin B12", "Vitamin C", "Vitamin D"], correctIndex: 3, category: "Science" },
  { question: "Which blood type is the universal donor?", options: ["A+", "AB+", "O-", "B-"], correctIndex: 2, category: "Science" },
  { question: "What is the closest star to Earth?", options: ["Proxima Centauri", "The Sun", "Alpha Centauri", "Sirius"], correctIndex: 1, category: "Science" },
  { question: "Sound travels fastest through which medium?", options: ["Air", "Water", "Steel", "Vacuum"], correctIndex: 2, category: "Science" },
  { question: "What is the study of earthquakes called?", options: ["Meteorology", "Seismology", "Volcanology", "Geography"], correctIndex: 1, category: "Science" },

  // History
  { question: "In what year did the Titanic sink?", options: ["1905", "1912", "1920", "1898"], correctIndex: 1, category: "History" },
  { question: "What year did the Berlin Wall fall?", options: ["1987", "1989", "1991", "1993"], correctIndex: 1, category: "History" },
  { question: "Who was the first person on the Moon?", options: ["Buzz Aldrin", "Yuri Gagarin", "Neil Armstrong", "John Glenn"], correctIndex: 2, category: "History" },
  { question: "Which ancient wonder was in Alexandria?", options: ["Hanging Gardens", "Lighthouse", "Colossus", "Temple of Artemis"], correctIndex: 1, category: "History" },
  { question: "Who was the first President of the United States?", options: ["Thomas Jefferson", "John Adams", "George Washington", "Benjamin Franklin"], correctIndex: 2, category: "History" },
  { question: "In which year did World War II end?", options: ["1943", "1944", "1945", "1946"], correctIndex: 2, category: "History" },
  { question: "Which empire built the Colosseum?", options: ["Greek", "Ottoman", "Roman", "Byzantine"], correctIndex: 2, category: "History" },
  { question: "Who was the famous queen of ancient Egypt?", options: ["Nefertiti", "Cleopatra", "Hatshepsut", "Isis"], correctIndex: 1, category: "History" },
  { question: "The Great Wall of China was mainly built to protect against whom?", options: ["Japanese", "Mongols", "Russians", "Koreans"], correctIndex: 1, category: "History" },
  { question: "Who painted the ceiling of the Sistine Chapel?", options: ["Leonardo da Vinci", "Raphael", "Michelangelo", "Botticelli"], correctIndex: 2, category: "History" },
  { question: "Which ship carried the Pilgrims to America in 1620?", options: ["Santa Maria", "Mayflower", "Endeavour", "Beagle"], correctIndex: 1, category: "History" },
  { question: "Who invented the telephone?", options: ["Thomas Edison", "Nikola Tesla", "Alexander Graham Bell", "Guglielmo Marconi"], correctIndex: 2, category: "History" },
  { question: "The French Revolution began in which year?", options: ["1776", "1789", "1799", "1812"], correctIndex: 1, category: "History" },
  { question: "Which civilization built Machu Picchu?", options: ["Aztec", "Maya", "Inca", "Olmec"], correctIndex: 2, category: "History" },
  { question: "Who was the British Prime Minister during most of World War II?", options: ["Neville Chamberlain", "Winston Churchill", "Clement Attlee", "Anthony Eden"], correctIndex: 1, category: "History" },

  // Art & Literature
  { question: "Who painted the Mona Lisa?", options: ["Michelangelo", "Raphael", "Leonardo da Vinci", "Donatello"], correctIndex: 2, category: "Art" },
  { question: "Who wrote 'Romeo and Juliet'?", options: ["Charles Dickens", "William Shakespeare", "Jane Austen", "Mark Twain"], correctIndex: 1, category: "Literature" },
  { question: "Who wrote '1984'?", options: ["Aldous Huxley", "George Orwell", "Ray Bradbury", "H.G. Wells"], correctIndex: 1, category: "Literature" },
  { question: "Which artist cut off part of his own ear?", options: ["Pablo Picasso", "Claude Monet", "Vincent van Gogh", "Salvador Dalí"], correctIndex: 2, category: "Art" },
  { question: "Who wrote 'Pride and Prejudice'?", options: ["Emily Brontë", "Jane Austen", "Charlotte Brontë", "Mary Shelley"], correctIndex: 1, category: "Literature" },
  { question: "What nationality was Pablo Picasso?", options: ["French", "Italian", "Spanish", "Portuguese"], correctIndex: 2, category: "Art" },
  { question: "Who wrote 'The Old Man and the Sea'?", options: ["John Steinbeck", "Ernest Hemingway", "F. Scott Fitzgerald", "William Faulkner"], correctIndex: 1, category: "Literature" },
  { question: "Which Shakespeare play features the characters Rosencrantz and Guildenstern?", options: ["Macbeth", "Othello", "Hamlet", "King Lear"], correctIndex: 2, category: "Literature" },
  { question: "Who created the famous sculpture 'The Thinker'?", options: ["Michelangelo", "Auguste Rodin", "Donatello", "Bernini"], correctIndex: 1, category: "Art" },
  { question: "In which museum is the Mona Lisa displayed?", options: ["The Met", "The Uffizi", "The Louvre", "The Prado"], correctIndex: 2, category: "Art" },

  // Sports
  { question: "Which country has the most World Cup wins?", options: ["Germany", "Italy", "Argentina", "Brazil"], correctIndex: 3, category: "Sports" },
  { question: "How many players are on a basketball team on the court?", options: ["4", "5", "6", "7"], correctIndex: 1, category: "Sports" },
  { question: "In which sport would you perform a slam dunk?", options: ["Volleyball", "Tennis", "Basketball", "Badminton"], correctIndex: 2, category: "Sports" },
  { question: "How often are the Summer Olympic Games held?", options: ["Every 2 years", "Every 3 years", "Every 4 years", "Every 5 years"], correctIndex: 2, category: "Sports" },
  { question: "Which country invented table tennis?", options: ["China", "Japan", "England", "Korea"], correctIndex: 2, category: "Sports" },
  { question: "What is the maximum score in a single frame of bowling?", options: ["20", "30", "40", "50"], correctIndex: 1, category: "Sports" },
  { question: "In tennis, what score comes after deuce?", options: ["Match point", "Advantage", "Game point", "Break point"], correctIndex: 1, category: "Sports" },
  { question: "Which boxer was known as 'The Greatest'?", options: ["Mike Tyson", "Muhammad Ali", "Floyd Mayweather", "Joe Frazier"], correctIndex: 1, category: "Sports" },
  { question: "How many rings are on the Olympic flag?", options: ["4", "5", "6", "7"], correctIndex: 1, category: "Sports" },
  { question: "In golf, what is one stroke under par called?", options: ["Eagle", "Bogey", "Birdie", "Albatross"], correctIndex: 2, category: "Sports" },

  // Entertainment & Music
  { question: "Which instrument has 88 keys?", options: ["Guitar", "Violin", "Piano", "Harp"], correctIndex: 2, category: "Music" },
  { question: "Which band wrote 'Bohemian Rhapsody'?", options: ["The Beatles", "Led Zeppelin", "Queen", "Pink Floyd"], correctIndex: 2, category: "Music" },
  { question: "How many strings does a standard guitar have?", options: ["4", "5", "6", "7"], correctIndex: 2, category: "Music" },
  { question: "Who is known as the 'King of Pop'?", options: ["Elvis Presley", "Michael Jackson", "Prince", "Freddie Mercury"], correctIndex: 1, category: "Music" },
  { question: "Which composer became deaf later in life?", options: ["Mozart", "Bach", "Beethoven", "Chopin"], correctIndex: 2, category: "Music" },
  { question: "Which movie features the quote 'May the Force be with you'?", options: ["Star Trek", "Star Wars", "Dune", "Interstellar"], correctIndex: 1, category: "Entertainment" },
  { question: "What is the highest-grossing film of all time (unadjusted)?", options: ["Titanic", "Avengers: Endgame", "Avatar", "Star Wars: The Force Awakens"], correctIndex: 2, category: "Entertainment" },
  { question: "Which streaming series is set in the town of Hawkins?", options: ["Dark", "Stranger Things", "Riverdale", "Wednesday"], correctIndex: 1, category: "Entertainment" },
  { question: "Who directed 'Jurassic Park'?", options: ["George Lucas", "James Cameron", "Steven Spielberg", "Ridley Scott"], correctIndex: 2, category: "Entertainment" },
  { question: "Which animated film features a clownfish named Marlin?", options: ["Shark Tale", "Finding Nemo", "Moana", "The Little Mermaid"], correctIndex: 1, category: "Entertainment" },

  // Nature & Food & Misc
  { question: "Which animal is the tallest in the world?", options: ["Elephant", "Giraffe", "Blue Whale", "Ostrich"], correctIndex: 1, category: "Nature" },
  { question: "What is the largest mammal?", options: ["African Elephant", "Blue Whale", "Giraffe", "Hippopotamus"], correctIndex: 1, category: "Nature" },
  { question: "What is the main ingredient in guacamole?", options: ["Tomato", "Avocado", "Lime", "Onion"], correctIndex: 1, category: "Food" },
  { question: "Which language has the most native speakers?", options: ["English", "Spanish", "Hindi", "Mandarin Chinese"], correctIndex: 3, category: "Language" },
  { question: "What is a group of lions called?", options: ["Pack", "Herd", "Pride", "Flock"], correctIndex: 2, category: "Nature" },
  { question: "How many hearts does an octopus have?", options: ["1", "2", "3", "4"], correctIndex: 2, category: "Nature" },
  { question: "Which fruit is known to have its seeds on the outside?", options: ["Raspberry", "Strawberry", "Blackberry", "Fig"], correctIndex: 1, category: "Food" },
  { question: "What is the national dish of Spain?", options: ["Tacos", "Pasta", "Paella", "Sushi"], correctIndex: 2, category: "Food" },
  { question: "Which bird is known for its ability to mimic human speech?", options: ["Crow", "Parrot", "Owl", "Sparrow"], correctIndex: 1, category: "Nature" },
  { question: "What is the only mammal capable of true flight?", options: ["Flying squirrel", "Bat", "Sugar glider", "Colugo"], correctIndex: 1, category: "Nature" },
  { question: "Which cheese is traditionally used on pizza Margherita?", options: ["Cheddar", "Gouda", "Mozzarella", "Parmesan"], correctIndex: 2, category: "Food" },
  { question: "Honey is made by bees from what?", options: ["Pollen", "Nectar", "Sap", "Dew"], correctIndex: 1, category: "Food" },
  { question: "What is the fastest land animal?", options: ["Lion", "Pronghorn", "Cheetah", "Greyhound"], correctIndex: 2, category: "Nature" },
  { question: "Which planet is closest to the Sun?", options: ["Venus", "Mercury", "Earth", "Mars"], correctIndex: 1, category: "Science" },
  { question: "Sushi originated in which country?", options: ["China", "Korea", "Japan", "Thailand"], correctIndex: 2, category: "Food" },

  // Technology
  { question: "Who co-founded Apple with Steve Jobs?", options: ["Bill Gates", "Steve Wozniak", "Elon Musk", "Mark Zuckerberg"], correctIndex: 1, category: "Technology" },
  { question: "What does 'HTTP' stand for?", options: ["HyperText Transfer Protocol", "High Tech Transfer Process", "HyperText Technical Program", "Home Tool Transfer Protocol"], correctIndex: 0, category: "Technology" },
  { question: "Which company created the Android operating system?", options: ["Apple", "Microsoft", "Google", "Samsung"], correctIndex: 2, category: "Technology" },
  { question: "What does 'CPU' stand for?", options: ["Central Processing Unit", "Computer Personal Unit", "Central Program Utility", "Core Processing Utility"], correctIndex: 0, category: "Technology" },
  { question: "In what decade was the World Wide Web invented?", options: ["1970s", "1980s", "1990s", "2000s"], correctIndex: 1, category: "Technology" },
  { question: "Which programming language is named after a snake?", options: ["Java", "Ruby", "Python", "Rust"], correctIndex: 2, category: "Technology" },
  { question: "What was the first widely-used web browser?", options: ["Internet Explorer", "Netscape Navigator", "Mosaic", "Firefox"], correctIndex: 2, category: "Technology" },
  { question: "How many bits are in a byte?", options: ["4", "8", "16", "32"], correctIndex: 1, category: "Technology" },
];
